kafka:
  streams:
    greetings-streams:
      input-topic: "greetings"
      properties:
        bootstrap.servers: "192.168.99.106:9092"
        application.id: "greetings-streams"
        acks: "all"
        cache.max.bytes.buffering: 0
        commit.interval.ms: 0
        retries: 100000
        
  publisher:
    properties:
      greetings-topic: "greetings"
      bootstrap.servers: "192.168.99.106:9092"
      acks: "all"
      enable.idempotence: "true"
      batch.size: "8000000"
      linger.ms: "5"
      client.id: "my-producer-id"